spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create

#    show-sql: true
    open-in-view: false
    properties:
#      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
